services:
  mysql:
    image: mysql:8
    container_name: movies-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
    ports:
      - "3306:3306"
    volumes:
      - movies-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  movies-db-data: